name: test-upgrade-on-boot

description: This is my personal OS image.

base-image: ghcr.io/secureblue/silverblue-main-hardened
image-version: latest
modules:
  - type: files
    files:
    - source: system
      destination: /

  - type: script
    scripts:
      - setplymouththemetext.sh
      - regenerateinitramfs.sh

  - type: signing 